apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-scraper-deployment
  labels:
    app: book-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-scraper
  template:
    metadata:
      labels:
        app: book-scraper
    spec:
      containers:
      - name: book-scraper
        image: marios1212/book-scraper-app:latest
        imagePullPolicy : Always
        stdin: true
        tty: true